spring:
  application:
    name: cold-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   # 开启路由
      routes: # 路由规则
        - id: cold-user-router
          uri: lb://cold-user
          predicates:
            - Path=/cold/sys/user/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    max-threads: 200
    min-spare-threads: 30
  connection-timeout: 30000ms
  servlet:
    context-path: /cold
